### ISSUE TITLE
Connect to remote redis

### ISSUE THREAD

**Issue by dm7pwnage** [chameleonbr/node-red-contrib-redis#36] opened 2020-07-22 13:10 UTC
Hi,

would you please provide an example how to connect to a remote redis on a different port including a password?

Whatever combination I enter in the field "server" I get the error: "Error: connect ECONNREFUSED 127.0.0.1:6379"

Thank you in advance!

Kind regards

**Comment by chameleonbr** [comment] 2020-07-22 15:29
Please see #35 some options to configure your redis server.  Duplicate of #35.

**Comment by chameleonbr** [comment] 2020-07-22 15:29
Duplicate of #35.

**Comment by chameleonbr** [comment] 2020-07-22 15:31
See the IORedis constructor parameters, https://github.com/luin/ioredis#connect-to-redis.

**Closed** 2020-07-22 15:34 UTC

**Comment by dm7pwnage** [comment] 2020-07-22 16:59
Thank you for your quick response.
